version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
  redis:  # Add this service
    image: redis:alpine
  db:    # New service
    image: postgres:alpine
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    ports:
      - "5432:5432"