name: Deploy Hello World

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yml'
      
jobs:
  deploy:
    name: SSH from Raspberry Pi to Local Server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into Local Server and Run Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.LOCAL_SERVER_HOST }}
          username: ${{ secrets.LOCAL_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/test
            git pull origin main
            docker-compose up -d --build
